name: Cypress Regression
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Execute Cypress Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace CI Configuration File
        env:
            CONFIG_DATA: ${{ toJSON(secrets.AUTOMATION_USERS) }}
        shell: bash
        run: |
          echo "Configuration data: $CONFIG_DATA"
          echo $(jq --argjson a '$CONFIG_DATA' '.users |= $a' config/ci.json) > config/ci.json 
          cat config/ci.json
      - name: Display config
        run: |
          cat config/ci.json
      - name: Run Cypress
        env:
          environment: "ci"
        run: |
          npm install
          npm run cy:run
      - name: Display Log
        run: |
          cat config/cypress.log