name: Cypress Regression
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Execute Cypress Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace CI Configuration File
        shell: bash
        run: |
          echo $(jq --arg a "${{ secrets.AUTOMATION_USERS }}" '.users = ($a)' config/ci.json) > config/ci.json 
      - name: Display config
        run: |
          cat config/ci.json
      - name: Run Cypress
        run: |
          npm run cy:run
      - name: Display Log
        run: |
          cat config/cypress.log